export const TOKEN_USER = "token";
export const EMAIL_USER = "email";
export const ADDRESS_USER = "address";
export const COMPANY_USER = "company_name";
export const NAME_USER = "name";
export const NPWP_USER = "npwp";
export const META_RECEIPT = "meta_receipt";

export const FORMAT_DATE_1 = "YYYY-MM-DD";

export const DEFAULT_ERROR_MESSAGE = "Ooops something wrong!";
export const INTERNAL_SERVER_ERROR = "Internal Server Error";
export const UNAUTHORIZED = "unauthorized";
export const UNAUTHORIZED_MESSAGE = "It looks like you're not logged in. Reload the page to try again";

export const AUTOGENERATED = "Autogenerated";
